language: c
script: ./autogen.sh && ./configure && make
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libusb-dev
install:
  - wget https://github.com/nfc-tools/libnfc/releases/download/libnfc-1.7.1/libnfc-1.7.1.tar.bz2
  - tar jxf libnfc-1.7.1.tar.bz2
  - pushd libnfc-1.7.1 && ./configure && make && sudo make install && popd

